### ISSUE TITLE
[ERROR] Cmake Build Error 

### ISSUE THREAD

**Issue by 827Dream** [trustdecision/td-ollvm#1]
there is no Headers folder in path /clang/lib，but this needed in cmakelist

https://github.com/trustdecision/td-ollvm/blob/9b3303e4cd55dd279a61bc970aaaf15bb9449452/clang/lib/CMakeLists.txt#L1

**Comment by zeinber** [comment]
Thank you for your feedback. We have updated the project. You can pull the latest code from the newest main branch and test it again.

**Comment by zeinber** [comment]
@827Dream
